replicaCount: 1

image:
  repository: geonetwork/geonetwork-ui-tools-pipelines
  tag: latest
  pullPolicy: Always

ingress:
  enabled: false

extra_environment:
  - name: ES_HOST
    value: "http://localhost:9200"
  - name: RECORDS_INDEX
    value: "geonetwork"

podAnnotations: {}

podSecurityContext: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

#lifecycle:
#  postStart:
#    exec:
#      command: ["/bin/sh", "-c", "echo Hello from the postStart handler > /usr/share/message"]
#  preStop:
#    exec:
#      command: ["/bin/sh","-c","nginx -s quit; while killall -0 nginx; do sleep 1; done"]

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi


nodeSelector: {}

tolerations: []

affinity: {}