{{- if .Values.ingress.enabled -}}
{{- $fullName := include "helm-datahub.fullname" . -}}
{{- if semverCompare ">=1.19-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}

kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "helm-datahub.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if and .Values.ingress.className (semverCompare ">=1.18-0" .Capabilities.KubeVersion.GitVersion) }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts | default (list "") }}
    {{- if $.Values.ingress.hosts }}
    - host: {{ .host | quote }}
    {{- else }}
    - host: {{ $.Values.fqdn | quote }}
    {{- end }}
      http:
        paths:
          - path: /
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "helm-datahub.fullname" $ }}-sp-svc
                port:
                  number: 8080
              {{- else }}
              serviceName: {{ include "helm-datahub.fullname" $ }}-sp-svc
              servicePort: 8080
              {{- end }}
          {{- if $.Values.helm-datahub.webapps.cas.enabled }}
          - path: /cas
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "helm-datahub.fullname" $ }}-cas-svc
                port:
                  number: 8080
              {{- else }}
              serviceName: {{ include "helm-datahub.fullname" $ }}-cas-svc
              servicePort: 8080
              {{- end }}
          {{- end }}
          {{- if and $.Values.helm-datahub.webapps.geonetwork.enabled $.Values.helm-datahub.webapps.geonetwork.ogc_api_records.enabled }}
          - path: /ogc-api-records
            {{- if semverCompare ">=1.18-0" $.Capabilities.KubeVersion.GitVersion }}
            pathType: Prefix
            {{- end }}
            backend:
              {{- if semverCompare ">=1.19-0" $.Capabilities.KubeVersion.GitVersion }}
              service:
                name: {{ include "helm-datahub.fullname" $ }}-gn4-ogc-api-records-svc
                port:
                  number: 8080
              {{- else }}
              serviceName: {{ include "helm-datahub.fullname" $ }}-gn4-ogc-api-records-svc
              servicePort: 8080
              {{- end }}
          {{- end }}
    {{- end }}
  {{- end }}
