apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "gn-tools-pipelines.fullname" . }}
  labels:
    {{ include "gn-tools-pipelines.labels" . | nindent 4 }}
spec:
  schedule: {{ .Values.job.schedule | quote }}
  successfulJobsHistoryLimit: {{ .Values.job.successfulJobsHistoryLimit }}
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: init
              image: "{{ .Values.config.image.repository }}:{{ .Values.config.image.tag }}"
              command: ['sh', '-c', 'while ! nc -z {{ .Values.config.service.host }} {{ .Values.config.service.port }}; do sleep 2; done']
          containers:
          - name: {{ include "gn-tools-pipelines.fullname" . }}
            image: "{{ .Values.job.image.repository }}:{{ .Values.job.image.tag | default .Chart.AppVersion }}"
            imagePullPolicy: {{ .Values.job.image.pullPolicy }}
            env:
              - name: ES_HOST
                value: {{ .Values.config.elasticsearch.host | required ".Values.config.elasticsearch.host is required." }}
              - name: ES_USERNAME
                value: {{ .Values.config.elasticsearch.username | quote }}
              - name: ES_PASSWORD
                value: {{ .Values.config.elasticsearch.password | quote }}
              - name: RECORDS_INDEX
                value: {{ .Values.config.elasticsearch.index | required ".Values.config.elasticsearch.index is required." }}
          restartPolicy: Never
          {{- with .Values.job.tolerations }}
          tolerations:
            {{-  toYaml . | nindent 10 }}
          {{- end }}
