replicaCount: 1

job:
  image:
    repository: geonetwork/geonetwork-ui-tools-pipelines
    tag: 2.6.2
    pullPolicy: IfNotPresent
  schedule: "0 1 1 1 *"
  successfulJobsHistoryLimit: 3
  restartPolicy: OnFailure
  tolerations: []

configuration:
  image:
    repository: curlimages/curl
    tag: latest

config:
  elasticsearch:
    host: "http://localhost:9200"
    index: "gn-records"
    service: "georchestra-gn4-elasticsearch-svc"